### ISSUE TITLE
Define "initial entries" for P4 tables, in addition to currently defined "const entries"

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#1159]
## Personnel
- [x] **Owner**: @jafingerhut 
- [x] **Supporters**: @thantry 

## Design
- [x] **Document**: https://docs.google.com/presentation/d/1GW-9FDtyLuwqV_mdGeDh_qqDiey0VkQ1/edit?usp=sharing&ouid=113165450274035133953&rtpof=true&sd=true

## Implementation
- [x] **`p4-spec`**: There are at least two different proposed syntaxes in two different PRs (1) https://github.com/p4lang/p4-spec/pull/1180 (2) https://github.com/p4lang/p4-spec/pull/1231 For a summary of differences see here https://github.com/p4lang/p4-spec/pull/1180#issuecomment-1504165720   At the 2023-May-01 LDWG meeting, there was general agreement preferring the backwards-compatible syntax extension decribed in #1180 over #1231
- [x] **`p4c`**: Step 1 of implementation, adding only the new parts of the grammar https://github.com/p4lang/p4c/pull/3748
- [x] **`p4c`**: Step 2 of implementation, generating correct P4Info file generated by p4c: https://github.com/p4lang/p4c/issues/4016 (must wait until P4 API work group approves how this feature is represented in P4Runtime API)
## Process
- [x] **LDWG discussed**: October 2022: https://docs.google.com/document/d/1XSgdXeG1UuF1FM_XAqxDrHeN4dHZWBnJPKVS6SnGNwM/edit#heading=h.37p6wudxij34
- [x] **LDWG approved**: Discussed last at 2023-May-01 LDWG meeting, and PR #1180 version was preferred over the alternative #1231
- [x] **Merged into `p4-spec`**: This PR was merged on 2023-May-15: https://github.com/p4lang/p4-spec/pull/1180
- [x] **Merged into `p4c`**: 

=======================================

**Comment by mihaibudiu** [comment]
https://github.com/p4lang/p4c/pull/3748 is the proof-of-concept, I will finalize it based on the accepted syntax.

**Comment by jnfoster** [comment]
Closing as the P4C PR has also been merged.
